FROM ubuntu:latest


# basic setup

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y \
  python3 \
  python3-dev \
  python3-pip

# setup Pillow

RUN pip3 install \
  numpy \
  pillow